version: "3.9"

services:
  app:
    build: .
    container_name: backend_app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
        - .:/app
    ports:
      - "8000:8000"
      - "5678:5678"
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data: